/**
 * Subset the typeface to the glyphs this plan actually uses, and commit them.
 *
 * Not an optimisation. Loading a CJK family from Google Fonts at render time
 * costs 196 requests **per browser tab**, and Remotion renders on several tabs
 * at once: one of them proceeded before its faces were ready, and every sixth
 * frame came out with no caption on it. Measured — at `REMOTION_CONCURRENCY=1`
 * the flicker disappears entirely.
 *
 * A local file removes the race rather than making it less likely.
 *
 * Regenerate after changing any on-screen copy:
 *   pnpm --filter @laris/render fonts
 *
 * Needs `uv`, which CONTRIBUTING already requires for the perception package.
 */
import { execFileSync } from "node:child_process";
import { existsSync, mkdirSync, readFileSync, statSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const pkg = join(here, "..");
const OUT = join(pkg, "public/fonts");

/** The SC face of Noto Sans CJK is index 2 of each collection. */
const FACES = [
  { weight: "400", src: "/usr/share/fonts/opentype/noto/NotoSansCJK-Regular.ttc" },
  { weight: "900", src: "/usr/share/fonts/opentype/noto/NotoSansCJK-Black.ttc" },
];
const FACE_INDEX = 2;

/** Latin, digits and punctuation that copy reaches for even when the plan does not. */
const ALWAYS = "0123456789 ·—–-…，。、：；！？（）「」《》%RM+/.,:;!?'\"&@#";

const plan = JSON.parse(readFileSync(join(pkg, "src/shot-plan.json"), "utf8"));
const copy = [
  plan.contact,
  ...plan.scenes.flatMap((s) => [s.headline, s.sub ?? "", s.tag ?? ""]),
  // The card sets two lines of its own.
  "15 个人，住一整栋",
  "邦咯岛 · 4 间房，每间自带卫浴 · 加床到 20 人",
  "整栋出租",
  ALWAYS,
].join("");

const glyphs = [...new Set([...copy])]
  .filter((c) => c !== "\n")
  .sort()
  .join("");

mkdirSync(OUT, { recursive: true });
for (const { weight, src } of FACES) {
  if (!existsSync(src)) {
    throw new Error(`missing ${src} — install fonts-noto-cjk (and -extra for Black)`);
  }
  const out = join(OUT, `noto-sans-sc-${weight}.woff2`);
  execFileSync(
    "uvx",
    [
      "--from",
      "fonttools",
      "--with",
      "brotli",
      "pyftsubset",
      src,
      `--font-number=${FACE_INDEX}`,
      `--text=${glyphs}`,
      "--layout-features=*",
      "--flavor=woff2",
      `--output-file=${out}`,
    ],
    { stdio: "inherit" },
  );
  console.log(
    `  ${weight}  ${(statSync(out).size / 1024).toFixed(1)} KB  ${out.replace(pkg, ".")}`,
  );
}
// Inlined as data URIs rather than served from `public/`.
//
// Every sixth frame of a render came out with no caption on it — the period of
// the browser-tab count. Subsetting and `delayRender` both failed to fix it,
// and a frame-by-frame comparison showed the photograph identical across the
// three frames while only the text vanished. Whatever the tab is racing with,
// a font that is already inside the bundle cannot lose that race.
const faces = FACES.map(({ weight }) => {
  const file = join(OUT, `noto-sans-sc-${weight}.woff2`);
  return `  "${weight}": "data:font/woff2;base64,${readFileSync(file).toString("base64")}",`;
}).join("\n");

writeFileSync(
  join(pkg, "src/font-data.ts"),
  `// GENERATED by scripts/build-fonts.mjs. Do not edit — run \`pnpm fonts\`.
//
// The typeface, subsetted to the ${glyphs.length} glyphs this plan puts on screen and
// inlined. See the script for why it is inlined rather than fetched.
export const GLYPHS = ${JSON.stringify(glyphs)};

export const WOFF2: Readonly<Record<"400" | "900", string>> = {
${faces}
};
`,
);
console.log(`${glyphs.length} glyphs → src/font-data.ts`);
