import type { BusinessContext } from "@laris/schema";

/**
 * Pangkor My Homestay — the first real Merchant.
 *
 * Everything here came from the owner or from their own marketing material.
 * Nothing is invented: where a fact is still unknown it is marked TODO rather
 * than filled with something plausible, because this Profile is what the
 * Merchant Site, the GBP listing and every later Channel are compiled from. A
 * plausible guess here becomes a wrong fact in four places.
 *
 * This is a whole-house rental, not a per-room one — see the single offering.
 */
export const pangkorMyHomestay: BusinessContext = {
  merchantId: "33333333-3333-4333-8333-333333333333",
  accountId: "44444444-4444-4444-8444-444444444444",
  vertical: "stay",

  identity: {
    name: "Pangkor My Homestay",
    // TODO(owner): confirm the street line. The GBP card reads "No. 21"; the
    // owner says the house is 23, so one of the two is wrong and the GBP is
    // the one guests navigate by.
    addressLines: ["No. 23, Jalan Pangkor Mutiara 2"],
    area: "Taman Pangkor Mutiara",
    postcode: "32300",
    // Pulau Pangkor is Perak — Kumpulan B, weekend Sat–Sun.
    state: "perak",
    phone: "+60125358226",
    whatsapp: "+60125358226",
    // TODO(owner): the Facebook page URL, once we have it.
    sameAs: [],
    // A whole-house rental has no opening hours. Left empty deliberately —
    // and note this is exactly the case that makes Drift Check report a
    // `certain` hours mismatch against every Channel (issue #7 review).
    hours: [],
  },

  verticalProfile: {
    stay: {
      landmarks: [
        { name: "海边", walkMin: 8 },
        // TODO(owner): the ad says "前面就有" — confirm the actual walk.
        { name: "7-Eleven、cafe、煮炒店", walkMin: 2 },
      ],
      // The owner has not said whether the house is listed on any OTA. Until
      // they do this stays empty, and the site cannot make a commission
      // argument — see the note in stay.ts about that being the value prop.
      otaListings: [],
    },
  },

  theme: {
    layout: "gallery-first",
    // Taken from the house itself: every room is painted this blue.
    accent: "#2F7FA8",
    typePair: "display-serif",
    density: "airy",
  },

  offerings: [
    {
      id: "whole-house",
      kind: "room_type",
      name: "整栋双层渡假屋",
      description:
        "4 间房(4人 / 4人 / 2人 / 2人),每间房内自带卫浴 · 小格楼 3 个床位 · " +
        "楼上楼下两个客厅,全冷气 · 7 架冷气、7 架风扇、4 架热水器 · " +
        "洗衣机、冰箱、过滤水机、电视、Astro、WiFi · " +
        "脚踏车、麻将台、K 歌免费用 · 加床一套 RM 20(枕头、被单、3×6 单人床),加到 20 人",
      capacityPax: 15,
      // TODO(owner): the one number that blocks everything else. Their own ad
      // says "<价格>假期或无假期决定" — so we need the weekday whole-house rate
      // here, and the holiday rate becomes a rateCalendar window. Left at 0 so
      // a half-filled Profile renders visibly broken instead of plausibly wrong.
      baseRateCents: 0,
      // Generated by deriveRateCalendar once baseRateCents is real.
      rateCalendar: [],
      minNights: 1,
      // TODO(owner): check-in / check-out times are still the schema defaults.
      checkin: "15:00",
      checkout: "12:00",
      // No enum value yet for the things that actually sell this house to a
      // group — bicycles, mahjong, karaoke, Astro. They live in the description
      // for now; see the note in the PR.
      // `bbq` is deliberately absent: it is available but costs extra, and the
      // amenity enum has no way to say that. Listing it would put a free
      // Barbecue into the JSON-LD Google reads. It stays in the FAQ instead.
      amenities: ["wifi", "aircon", "kitchen", "washer", "tv", "parking"],
      photos: [],
      isSignature: true,
    },
  ],

  // Filled by withDerivedCalendar() from mycal once this merchant is live.
  calendar: [],

  faq: [
    {
      q: "最少要住几晚？",
      a: "一晚就可以，没有最低住宿限制。",
      source: "merchant",
    },
    {
      q: "可以住几个人？",
      a: "整栋出租，12 到 15 人。要再多可以加床，一套 RM 20（枕头、被单、3×6 单人床），加到 20 人没问题。",
      source: "merchant",
    },
    {
      q: "可以自己煮吗？",
      a: "可以，厨房齐全，冰箱、过滤水机、煮热水器都有。想烧烤的话我们也可以帮你准备 BBQ，另外算钱。",
      source: "merchant",
    },
    {
      q: "脚踏车、麻将台要另外给钱吗？",
      a: "不用，脚踏车、麻将台和 K 歌都是免费用的。",
      source: "merchant",
    },
    {
      q: "怎么去？",
      a: "从 Lumut 码头或 Marina 码头搭船进邦咯岛。上岛之后可以租摩托自己驾，也可以租车，或者叫 taxi van，都找得到。",
      source: "merchant",
    },
    {
      q: "附近有得吃吗？",
      a: "屋子前面就有小食店、cafe 和煮炒店，7-Eleven 也在附近。走路 8 分钟就到海边。",
      source: "merchant",
    },
  ],

  watchlist: [],
  photos: [],
  updatedAt: "2026-09-01T00:00:00.000Z",
};
