import type { BusinessContext } from "@laris/schema";

/**
 * Pangkor My Homestay — the first real Merchant.
 *
 * Everything here came from the owner or from their own marketing material.
 * Nothing is invented: where a fact is still unknown it is marked TODO rather
 * than filled with something plausible, because this Profile is what the
 * Merchant Site, the GBP listing and every later Channel are compiled from. A
 * plausible guess here becomes a wrong fact in four places.
 *
 * This is a whole-house rental, not a per-room one — see the single offering.
 */
export const pangkorMyHomestay: BusinessContext = {
  merchantId: "33333333-3333-4333-8333-333333333333",
  accountId: "44444444-4444-4444-8444-444444444444",
  vertical: "stay",

  identity: {
    // Exactly as the Google Business Profile reads it today. The domain says
    // "pangkormyhomestay" and Facebook says something third — that disagreement
    // is real and needs settling, but not before the GBP API application: a
    // name change can trigger re-verification, and the prerequisite is a
    // profile verified and active for 60+ days.
    name: "邦咯岛渡假屋No.23双层屋",
    // Verified against the Business Profile itself, 2026-09-01.
    addressLines: ["No. 23, Jalan Pangkor Mutiara 2"],
    area: "Taman Pangkor Mutiara",
    postcode: "32300",
    // Pulau Pangkor is Perak — Kumpulan B, weekend Sat–Sun.
    state: "perak",
    phone: "+60125358226",
    whatsapp: "+60125358226",
    // TODO(owner): the Facebook page URL, once we have it.
    sameAs: ["https://maps.google.com/?cid=8495038843976437085"],
    // A whole-house rental has no opening hours. Left empty deliberately —
    // and note this is exactly the case that makes Drift Check report a
    // `certain` hours mismatch against every Channel (issue #7 review).
    hours: [],
  },

  verticalProfile: {
    stay: {
      // Measured on Google Maps rather than taken from her advertising, which
      // says "步行8分钟到海边". The beach is 950 m and thirteen minutes on foot.
      // Five minutes of Malaysian midday is the difference between a guest who
      // was told the truth and a guest writing a review about it.
      landmarks: [
        { name: "Pasir Bogak 海滩", walkMin: 13, driveMin: 3 },
        { name: "7-Eleven", walkMin: 2 },
        { name: "Sea Moon Cafe", walkMin: 3 },
        { name: "潮盛海鲜餐室", walkMin: 11 },
        // Nobody walks 1.8 km from the ferry with luggage.
        { name: "邦咯岛码头 Pangkor Island Jetty", driveMin: 5 },
      ],
      // Empty because the house is on no OTA at all — every booking is direct,
      // through WhatsApp and word of mouth. Not a gap in the data: it means
      // directBookingSavingCents() has nothing to compute for this merchant,
      // and the commission argument stay.ts calls the value proposition does
      // not apply to the first business we put on the product.
      otaListings: [],
    },
  },

  theme: {
    layout: "gallery-first",
    // Taken from the house itself: every room is painted this blue.
    accent: "#2F7FA8",
    typePair: "display-serif",
    density: "airy",
  },

  offerings: [
    {
      id: "whole-house",
      kind: "room_type",
      name: "整栋双层渡假屋",
      description:
        "4 间房(4人 / 4人 / 2人 / 2人),每间房内自带卫浴 · 小格楼 3 个床位 · " +
        "楼上楼下两个客厅,全冷气 · 7 架冷气、7 架风扇、4 架热水器 · " +
        "洗衣机、冰箱、过滤水机、电视、Astro、WiFi · " +
        "脚踏车、麻将台、K 歌免费用 · 加床一套 RM 20(枕头、被单、3×6 单人床),加到 20 人",
      capacityPax: 15,
      isWholePlace: true,
      bedrooms: 4,
      // No baseRateCents: she quotes on enquiry and has never had a rate card.
      // The one number we have — RM 550 for a 28th-to-29th stay — reads either
      // as a weekday floor or a school-holiday ceiling depending on the month,
      // and the two are 40% apart. An inferred rate stored here would be read
      // as fact by the rate calendar and by every Channel downstream.
      // Generated by deriveRateCalendar once baseRateCents is real.
      rateCalendar: [],
      minNights: 1,
      // checkin/checkout omitted: not asked yet, and 15:00 is a schema default,
      // not an answer. The site says what it knows and stays quiet on the rest.
      // No enum value yet for the things that actually sell this house to a
      // group — bicycles, mahjong, karaoke, Astro. They live in the description
      // for now; see the note in the PR.
      // `bbq` is deliberately absent: it is available but costs extra, and the
      // amenity enum has no way to say that. Listing it would put a free
      // Barbecue into the JSON-LD Google reads. It stays in the FAQ instead.
      amenities: ["wifi", "aircon", "kitchen", "washer", "tv", "parking"],
      photos: [
        {
          key: "pangkor-my-homestay/room-double",
          width: 720,
          height: 960,
          widths: [720],
          alt: "双人房 · 冷气、风扇，房内自带卫浴",
        },
        {
          key: "pangkor-my-homestay/room-twin",
          width: 960,
          height: 839,
          widths: [960],
          alt: "四人房 · 两张床并排",
        },
        {
          key: "pangkor-my-homestay/loft-beds",
          width: 960,
          height: 720,
          widths: [960],
          alt: "小格楼床位",
        },
      ],
      isSignature: true,
    },
  ],

  // Filled by withDerivedCalendar() from mycal once this merchant is live.
  calendar: [],

  faq: [
    {
      q: "最少要住几晚？",
      a: "一晚就可以，没有最低住宿限制。",
      source: "merchant",
    },
    {
      q: "可以住几个人？",
      a: "整栋出租，12 到 15 人。要再多可以加床，一套 RM 20（枕头、被单、3×6 单人床），加到 20 人没问题。",
      source: "merchant",
    },
    {
      q: "可以自己煮吗？",
      a: "可以，厨房齐全，冰箱、过滤水机、煮热水器都有。想烧烤的话我们也可以帮你准备 BBQ，另外算钱。",
      source: "merchant",
    },
    {
      q: "脚踏车、麻将台要另外给钱吗？",
      a: "不用，脚踏车、麻将台和 K 歌都是免费用的。",
      source: "merchant",
    },
    {
      q: "怎么去？",
      a: "从 Lumut 码头或 Marina 码头搭船进邦咯岛。上岛后从码头到屋子 1.8 公里，开车大概 5 分钟。码头有 taxi van，也可以租摩托或租车自己驾。",
      source: "merchant",
    },
    {
      q: "附近有得吃吗？",
      a: "7-Eleven 走路 2 分钟，Sea Moon Cafe 3 分钟，潮盛海鲜餐室 11 分钟。走路 13 分钟到 Pasir Bogak 海滩，开车 3 分钟。",
      source: "merchant",
    },
    {
      q: "可以带猪肉和酒进来吗？",
      a: "可以。这间屋子不是清真的，厨房也没有分开的器具，所以自己煮什么、带什么酒来都没问题。介意的话订房前先跟我们说。",
      source: "merchant",
    },
  ],

  watchlist: [],

  // The owner's own photographs. Their two marketing collages are deliberately
  // left out: the phone number is burned into the image, which makes it a fact
  // no Profile edit can ever reach.
  photos: [
    {
      key: "pangkor-my-homestay/frontage-sky",
      width: 1080,
      height: 740,
      widths: [1080],
      alt: "屋子正面 · 双层排屋，有遮阳棚和停车位",
    },
    {
      key: "pangkor-my-homestay/living-room",
      width: 1080,
      height: 810,
      widths: [1080],
      alt: "楼下客厅 · 冷气、电视、Astro",
    },
    {
      key: "pangkor-my-homestay/room-balcony",
      width: 960,
      height: 720,
      widths: [960],
      alt: "楼上房间 · 两张床，外面连着阳台",
    },
    {
      key: "pangkor-my-homestay/loft-stairs",
      width: 720,
      height: 960,
      widths: [720],
      alt: "小格楼 · 三个床位，木楼梯上去",
    },
    {
      key: "pangkor-my-homestay/mahjong",
      width: 1040,
      height: 1080,
      widths: [1040],
      alt: "麻将台和扑克牌，免费用",
    },
    {
      key: "pangkor-my-homestay/frontage",
      width: 960,
      height: 720,
      widths: [960],
      alt: "屋前停车位 · 脚踏车免费借",
    },
    {
      key: "pangkor-my-homestay/room-ensuite",
      width: 720,
      height: 960,
      widths: [720],
      alt: "房间自带卫浴",
    },
  ],
  updatedAt: "2026-09-01T00:00:00.000Z",
};
