import { existsSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { describe, expect, it } from "vitest";
import { GLYPHS, WOFF2 } from "./font-data.js";
import { ShotPlan } from "./shot-plan.js";
import planJson from "./shot-plan.json";

const here = dirname(fileURLToPath(import.meta.url));
const photos = join(here, "../../api/public/m/pangkor-my-homestay");
const vo = join(here, "../public/vo");

/**
 * The plan is generated and committed, which is the point — a wrong scene
 * colour or a line pointing at the wrong room should be a diff, not something
 * you find by watching thirty seconds of video. That only works if the
 * committed file is checked.
 */
describe("the committed shot plan", () => {
  const plan = ShotPlan.parse(planJson);
  const frames = plan.scenes.flatMap((s) => s.frames);

  it("parses against its own schema", () => {
    expect(plan.scenes.length).toBeGreaterThan(0);
  });

  it("names photographs that exist in the Merchant's own assets", () => {
    // `public/photos/` here is a copy made by `pnpm plan` and is gitignored;
    // the originals live with the Merchant, and that is what must resolve on a
    // fresh clone.
    for (const frame of frames) {
      expect(existsSync(join(photos, frame.photo)), frame.photo).toBe(true);
    }
  });

  it("has a committed take behind every scene that claims audio", () => {
    // `public/vo/*.mp3` is generated by `pnpm voice`; the raw takes beside them
    // are what is committed, because re-fetching them costs API credits and a
    // clone without them renders silent with the wrong timing.
    for (const scene of plan.scenes) {
      if (!scene.audio) continue;
      const take = join(vo, "raw", scene.audio.replace(/^vo\//, ""));
      expect(existsSync(take), `missing take for ${scene.headline}`).toBe(true);
    }
  });

  it("gives every scene a colour dark enough for white type", () => {
    for (const { color, headline } of plan.scenes) {
      const [r, g, b] = [1, 3, 5].map((i) => Number.parseInt(color.slice(i, i + 2), 16));
      const luminance = (0.2126 * (r ?? 0) + 0.7152 * (g ?? 0) + 0.0722 * (b ?? 0)) / 255;
      expect(luminance, `${headline} ${color}`).toBeLessThan(0.4);
    }
  });

  it("cuts the picture faster than the voice", () => {
    // One photograph per sentence is a slideshow. The binding constraint here
    // is that ten photographs exist and several lines have only one that
    // honestly illustrates them — so this is 3.3s, not the 2s a reel wants.
    // Tighten it when there is real footage to cut with.
    const total = plan.scenes.reduce((n, s) => n + s.durationMs, 0);
    expect(total / frames.length).toBeLessThan(3500);
  });

  it("never narrates something the photographs cannot show", () => {
    // Asserted per scene. The version of this test that joined every line into
    // one string and anchored on the end could only ever fail on the last
    // scene, so it passed while the beach claim was still in the voice.
    //
    // These are the subjects no photograph in this set supports: there is no
    // kitchen, no barbecue, no beach and nobody in any of the ten.
    const UNSUPPORTED = /厨房|烧烤|海滩|沙滩/;
    for (const scene of plan.scenes) {
      expect(scene.spoken, `${scene.headline}: ${scene.spoken}`).not.toMatch(UNSUPPORTED);
    }
  });

  it("opens on the hook and closes on the call to action", () => {
    expect(plan.scenes[0]?.headline).toBe("最怕分开住");
    expect(plan.scenes.at(-1)?.tag).toBeDefined();
    expect(plan.scenes.at(-1)?.sub).toContain(plan.contact);
  });
});

describe("the subsetted typeface", () => {
  const plan = ShotPlan.parse(planJson);

  it("is inlined rather than fetched at render time", () => {
    // Anything a browser tab has to go and get, one of six tabs will render
    // without. That is what produced a caption missing from every sixth frame.
    for (const weight of ["400", "900"] as const) {
      expect(WOFF2[weight].startsWith("data:font/woff2;base64,")).toBe(true);
      expect(WOFF2[weight].length).toBeGreaterThan(10_000);
    }
  });

  it("covers every character the plan puts on screen", () => {
    // A headline with a character nobody regenerated for renders as tofu, and
    // nothing else would catch it.
    const have = new Set([...GLYPHS]);
    const copy = [
      plan.contact,
      ...plan.scenes.flatMap((s) => [s.headline, s.sub ?? "", s.tag ?? ""]),
    ].join("");

    const missing = [...new Set([...copy])].filter((c) => c !== "\n" && !have.has(c));
    expect(missing.join(""), "run `pnpm --filter @laris/render fonts`").toBe("");
  });
});

describe("the music bed", () => {
  const plan = ShotPlan.parse(planJson);

  it("knows when the voice actually speaks, not just how long the scene is", () => {
    // The bed ducks against `speechMs`. Ducking against `durationMs` would hold
    // the music down through the tail of silence that exists so the cut lands
    // in a breath — the one moment the bed should be audible.
    for (const scene of plan.scenes) {
      if (!scene.audio) continue;
      expect(scene.speechMs, scene.headline).toBeGreaterThan(0);
      expect(scene.speechMs, scene.headline).toBeLessThan(scene.durationMs);
    }
  });

  it("ships no track", () => {
    // Borrowing one is how a merchant collects a copyright claim on their own
    // listing. `music` appears only once a licensed file is really there.
    expect(existsSync(join(here, "../public/music/bed.mp3"))).toBe(plan.music !== undefined);
  });
});
